
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - ./buildspec.sh

  build:
    commands:
      - npm run build
      - npm run -- cdk deploy --ci --require-approval never -a "npx ts-node bin/app.ts" Monenv*
artifacts:
  files:
    - "cdk.out/**/*"
